# analysis_options.yaml for Crafted By Her Flutter project
# Configures Dart analyzer and linting rules for code quality

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Enforce null safety
    invalid_null_aware_operator: error
    # Ensure type safety
    invalid_use_of_protected_member: error
  exclude:
    # Ignore generated files
    - build/**
    - lib/generated/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    # Ignore test files if not linting tests
    - test/**

linter:
  rules:
    # Enforce consistent naming conventions
    - camel_case_types
    - library_private_types_in_public_api
    - non_constant_identifier_names
    # Improve code readability
    - always_declare_return_types
    - avoid_empty_else
    - avoid_redundant_argument_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    # Flutter-specific best practices
    - always_use_package_imports
    - avoid_dynamic_calls
    - use_build_context_synchronously
    - prefer_relative_imports
    # Prevent common errors
    - avoid_returning_null_for_future
    - avoid_unnecessary_containers
    - unnecessary_nullable_for_final_variable_declarations
    # Enforce null safety
    - unnecessary_null_comparison
    - null_check_on_nullable_type_parameter
    # Disable rules that may conflict with project style
    - lines_longer_than_80_chars: false
    - require_trailing_commas: false