name: crafted_by_her
description: A mobile app for the Crafted By Her Safaricom Capstone Project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  mockito: ^5.4.2
  flutter_svg: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter_rating_bar: ^4.0.1
  youtube_player_flutter: ^9.1.1
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  image: ^4.5.4
  http_parser: ^4.1.2
  mime: ^2.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  retry: ^3.1.2
  connectivity_plus: ^6.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  riverpod_generator: ^2.6.1


flutter:
  uses-material-design: true
  fonts:
    - family: DMSerif
      fonts:
        - asset: assets/font/DMSerifDisplay-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-VariableFont_wdth,wght.ttf

    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-VariableFont_wdth,wght.ttf
  assets:
    - assets/icon/
    - assets/images/
    - assets/font/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"